apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: example
  namespace: foo
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: basic-api
              servicePort: 5556
            path: /status
